import { createContext, useContext } from "react";

// Action Types Constants
export const CANVAS_ACTIONS = {
  SET_CONNECTED: 'SET_CONNECTED',
  UPDATE_CANVAS_STATE: 'UPDATE_CANVAS_STATE',
  UPDATE_CANVAS_DATA: 'UPDATE_CANVAS_DATA',
  UPDATE_CANVAS_STATS: 'UPDATE_CANVAS_STATS',
  SET_SELECTED_COLOR: 'SET_SELECTED_COLOR',
  SET_PAINTING: 'SET_PAINTING',
  ADD_USER: 'ADD_USER',
  REMOVE_USER: 'REMOVE_USER',
  SET_JOINED: 'SET_JOINED',
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  RESET_CANVAS: 'RESET_CANVAS',
  LEAVE_CANVAS: 'LEAVE_CANVAS'
};

export const USER_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PIXELS_PAINTED: 'UPDATE_PIXELS_PAINTED'
};

export const StoreContext = createContext();
export const useStore = () => useContext(StoreContext);